spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jimmer-sql-graphql;database_to_upper=true

jimmer:
  show-sql: true

demo:
  default-tenant: a